name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.16.0]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Node ${{ matrix.node-version }} and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Install Deps
        run: yarn install --frozen-lockfile

      - name: Start Dgraph
        run: yarn database:start && sleep 20

      - name: Write Env
        run: cp .env.development .env

      - name: Push Schema
        run: yarn schema:push

      - name: Run Codegen
        run: yarn graphql:build

      - name: Typecheck
        run: yarn types:check

      - name: Build Website
        run: yarn web:build
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      - name: Stop Dgraph
        run: docker-compose down
